spring:
  datasource:
    url: jdbc:mysql://localhost:3306/post
    username: root
    password: 12345678

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

org.springframework:
  orm.jpa: DEBUG
  transaction: DEBUG
  security.web.FilterChainProxy: DEBUG

jwt:
  secret-key: "some_secret_key"
  validity-in-hour: 120 # hour
